// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/audio_db.dart';
import 'api/audio_info.dart';
import 'api/scanner.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 791080442;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_myapp',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiAudioDbDbManagerAddSongToPlaylist({
    required DbManager that,
    required String playlistId,
    required String musicId,
  });

  Future<void> crateApiAudioDbDbManagerAddToHistory({
    required DbManager that,
    required String musicId,
  });

  Future<void> crateApiAudioDbDbManagerClearHistory({required DbManager that});

  Future<void> crateApiAudioDbDbManagerCreatePlaylist({
    required DbManager that,
    required String name,
    String? description,
    required bool isSystem,
  });

  Future<void> crateApiAudioDbDbManagerDeletePlaylist({
    required DbManager that,
    required String playlistId,
  });

  Future<void> crateApiAudioDbDbManagerDeleteSongCompletely({
    required DbManager that,
    required String musicId,
  });

  Future<List<PlaylistInfo>> crateApiAudioDbDbManagerGetAllPlaylists({
    required DbManager that,
  });

  Future<List<MusicInfo>> crateApiAudioDbDbManagerGetFavoriteSongs({
    required DbManager that,
  });

  Future<List<MusicInfo>> crateApiAudioDbDbManagerGetPlayHistory({
    required DbManager that,
  });

  Future<MusicInfo?> crateApiAudioDbDbManagerGetSong({
    required DbManager that,
    required String id,
  });

  Future<List<String>> crateApiAudioDbDbManagerGetSongIdsInPlaylist({
    required DbManager that,
    required String playlistId,
  });

  Future<List<MusicInfo>> crateApiAudioDbDbManagerGetSongsInPlaylist({
    required DbManager that,
    required String playlistId,
  });

  Future<void> crateApiAudioDbDbManagerInsertSong({
    required DbManager that,
    required MusicInfo music,
  });

  Future<void> crateApiAudioDbDbManagerInsertSongsBulk({
    required DbManager that,
    required List<MusicInfo> songs,
  });

  Future<bool> crateApiAudioDbDbManagerIsSongFavorited({
    required DbManager that,
    required String musicId,
  });

  Future<DbManager> crateApiAudioDbDbManagerNew({required String dbPath});

  Future<void> crateApiAudioDbDbManagerRemoveSongFromPlaylist({
    required DbManager that,
    required String playlistId,
    required String musicId,
  });

  Future<bool> crateApiAudioDbDbManagerToggleSongFavorite({
    required DbManager that,
    required String musicId,
  });

  Future<void> crateApiAudioDbDbManagerUpdatePlaylist({
    required DbManager that,
    required String name,
    String? description,
    String? coverPath,
  });

  Future<List<LyricLine>> crateApiAudioInfoAudioInfoParseLrc({
    String? lrcContent,
  });

  Future<AudioInfo> crateApiAudioInfoGetAudioInfo({required String path});

  Future<String> crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Stream<AudioMetadata> crateApiScannerScanDirectoryParallel({
    required String dirPath,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_DbManager;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_DbManager;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_DbManagerPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiAudioDbDbManagerAddSongToPlaylist({
    required DbManager that,
    required String playlistId,
    required String musicId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
            that,
            serializer,
          );
          sse_encode_String(playlistId, serializer);
          sse_encode_String(musicId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerAddSongToPlaylistConstMeta,
        argValues: [that, playlistId, musicId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerAddSongToPlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "DbManager_add_song_to_playlist",
        argNames: ["that", "playlistId", "musicId"],
      );

  @override
  Future<void> crateApiAudioDbDbManagerAddToHistory({
    required DbManager that,
    required String musicId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
            that,
            serializer,
          );
          sse_encode_String(musicId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerAddToHistoryConstMeta,
        argValues: [that, musicId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerAddToHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "DbManager_add_to_history",
        argNames: ["that", "musicId"],
      );

  @override
  Future<void> crateApiAudioDbDbManagerClearHistory({required DbManager that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerClearHistoryConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerClearHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "DbManager_clear_history",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiAudioDbDbManagerCreatePlaylist({
    required DbManager that,
    required String name,
    String? description,
    required bool isSystem,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          sse_encode_opt_String(description, serializer);
          sse_encode_bool(isSystem, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerCreatePlaylistConstMeta,
        argValues: [that, name, description, isSystem],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerCreatePlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "DbManager_create_playlist",
        argNames: ["that", "name", "description", "isSystem"],
      );

  @override
  Future<void> crateApiAudioDbDbManagerDeletePlaylist({
    required DbManager that,
    required String playlistId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
            that,
            serializer,
          );
          sse_encode_String(playlistId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerDeletePlaylistConstMeta,
        argValues: [that, playlistId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerDeletePlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "DbManager_delete_playlist",
        argNames: ["that", "playlistId"],
      );

  @override
  Future<void> crateApiAudioDbDbManagerDeleteSongCompletely({
    required DbManager that,
    required String musicId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
            that,
            serializer,
          );
          sse_encode_String(musicId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerDeleteSongCompletelyConstMeta,
        argValues: [that, musicId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerDeleteSongCompletelyConstMeta =>
      const TaskConstMeta(
        debugName: "DbManager_delete_song_completely",
        argNames: ["that", "musicId"],
      );

  @override
  Future<List<PlaylistInfo>> crateApiAudioDbDbManagerGetAllPlaylists({
    required DbManager that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_playlist_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerGetAllPlaylistsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerGetAllPlaylistsConstMeta =>
      const TaskConstMeta(
        debugName: "DbManager_get_all_playlists",
        argNames: ["that"],
      );

  @override
  Future<List<MusicInfo>> crateApiAudioDbDbManagerGetFavoriteSongs({
    required DbManager that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_music_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerGetFavoriteSongsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerGetFavoriteSongsConstMeta =>
      const TaskConstMeta(
        debugName: "DbManager_get_favorite_songs",
        argNames: ["that"],
      );

  @override
  Future<List<MusicInfo>> crateApiAudioDbDbManagerGetPlayHistory({
    required DbManager that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_music_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerGetPlayHistoryConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerGetPlayHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "DbManager_get_play_history",
        argNames: ["that"],
      );

  @override
  Future<MusicInfo?> crateApiAudioDbDbManagerGetSong({
    required DbManager that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_music_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerGetSongConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerGetSongConstMeta =>
      const TaskConstMeta(
        debugName: "DbManager_get_song",
        argNames: ["that", "id"],
      );

  @override
  Future<List<String>> crateApiAudioDbDbManagerGetSongIdsInPlaylist({
    required DbManager that,
    required String playlistId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
            that,
            serializer,
          );
          sse_encode_String(playlistId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerGetSongIdsInPlaylistConstMeta,
        argValues: [that, playlistId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerGetSongIdsInPlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "DbManager_get_song_ids_in_playlist",
        argNames: ["that", "playlistId"],
      );

  @override
  Future<List<MusicInfo>> crateApiAudioDbDbManagerGetSongsInPlaylist({
    required DbManager that,
    required String playlistId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
            that,
            serializer,
          );
          sse_encode_String(playlistId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_music_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerGetSongsInPlaylistConstMeta,
        argValues: [that, playlistId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerGetSongsInPlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "DbManager_get_songs_in_playlist",
        argNames: ["that", "playlistId"],
      );

  @override
  Future<void> crateApiAudioDbDbManagerInsertSong({
    required DbManager that,
    required MusicInfo music,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
            that,
            serializer,
          );
          sse_encode_box_autoadd_music_info(music, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerInsertSongConstMeta,
        argValues: [that, music],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerInsertSongConstMeta =>
      const TaskConstMeta(
        debugName: "DbManager_insert_song",
        argNames: ["that", "music"],
      );

  @override
  Future<void> crateApiAudioDbDbManagerInsertSongsBulk({
    required DbManager that,
    required List<MusicInfo> songs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
            that,
            serializer,
          );
          sse_encode_list_music_info(songs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerInsertSongsBulkConstMeta,
        argValues: [that, songs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerInsertSongsBulkConstMeta =>
      const TaskConstMeta(
        debugName: "DbManager_insert_songs_bulk",
        argNames: ["that", "songs"],
      );

  @override
  Future<bool> crateApiAudioDbDbManagerIsSongFavorited({
    required DbManager that,
    required String musicId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
            that,
            serializer,
          );
          sse_encode_String(musicId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerIsSongFavoritedConstMeta,
        argValues: [that, musicId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerIsSongFavoritedConstMeta =>
      const TaskConstMeta(
        debugName: "DbManager_is_song_favorited",
        argNames: ["that", "musicId"],
      );

  @override
  Future<DbManager> crateApiAudioDbDbManagerNew({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerNewConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerNewConstMeta =>
      const TaskConstMeta(debugName: "DbManager_new", argNames: ["dbPath"]);

  @override
  Future<void> crateApiAudioDbDbManagerRemoveSongFromPlaylist({
    required DbManager that,
    required String playlistId,
    required String musicId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
            that,
            serializer,
          );
          sse_encode_String(playlistId, serializer);
          sse_encode_String(musicId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerRemoveSongFromPlaylistConstMeta,
        argValues: [that, playlistId, musicId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerRemoveSongFromPlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "DbManager_remove_song_from_playlist",
        argNames: ["that", "playlistId", "musicId"],
      );

  @override
  Future<bool> crateApiAudioDbDbManagerToggleSongFavorite({
    required DbManager that,
    required String musicId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
            that,
            serializer,
          );
          sse_encode_String(musicId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerToggleSongFavoriteConstMeta,
        argValues: [that, musicId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerToggleSongFavoriteConstMeta =>
      const TaskConstMeta(
        debugName: "DbManager_toggle_song_favorite",
        argNames: ["that", "musicId"],
      );

  @override
  Future<void> crateApiAudioDbDbManagerUpdatePlaylist({
    required DbManager that,
    required String name,
    String? description,
    String? coverPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          sse_encode_opt_String(description, serializer);
          sse_encode_opt_String(coverPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAudioDbDbManagerUpdatePlaylistConstMeta,
        argValues: [that, name, description, coverPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioDbDbManagerUpdatePlaylistConstMeta =>
      const TaskConstMeta(
        debugName: "DbManager_update_playlist",
        argNames: ["that", "name", "description", "coverPath"],
      );

  @override
  Future<List<LyricLine>> crateApiAudioInfoAudioInfoParseLrc({
    String? lrcContent,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(lrcContent, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_lyric_line,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioInfoAudioInfoParseLrcConstMeta,
        argValues: [lrcContent],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioInfoAudioInfoParseLrcConstMeta =>
      const TaskConstMeta(
        debugName: "audio_info_parse_lrc",
        argNames: ["lrcContent"],
      );

  @override
  Future<AudioInfo> crateApiAudioInfoGetAudioInfo({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_audio_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAudioInfoGetAudioInfoConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioInfoGetAudioInfoConstMeta =>
      const TaskConstMeta(debugName: "get_audio_info", argNames: ["path"]);

  @override
  Future<String> crateApiSimpleGreet({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Stream<AudioMetadata> crateApiScannerScanDirectoryParallel({
    required String dirPath,
  }) {
    final sink = RustStreamSink<AudioMetadata>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(dirPath, serializer);
            sse_encode_StreamSink_audio_metadata_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 24,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiScannerScanDirectoryParallelConstMeta,
          argValues: [dirPath, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiScannerScanDirectoryParallelConstMeta =>
      const TaskConstMeta(
        debugName: "scan_directory_parallel",
        argNames: ["dirPath", "sink"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_DbManager => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_DbManager => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  DbManager
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DbManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  DbManager
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DbManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  DbManager
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DbManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<AudioMetadata> dco_decode_StreamSink_audio_metadata_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AudioInfo dco_decode_audio_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AudioInfo(
      title: dco_decode_String(arr[0]),
      artist: dco_decode_String(arr[1]),
      album: dco_decode_String(arr[2]),
      durationSeconds: dco_decode_u_32(arr[3]),
      coverArt: dco_decode_opt_list_prim_u_8_strict(arr[4]),
    );
  }

  @protected
  AudioMetadata dco_decode_audio_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AudioMetadata(
      title: dco_decode_String(arr[0]),
      artist: dco_decode_String(arr[1]),
      album: dco_decode_String(arr[2]),
      durationSeconds: dco_decode_u_32(arr[3]),
      path: dco_decode_String(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  MusicInfo dco_decode_box_autoadd_music_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_music_info(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<LyricLine> dco_decode_list_lyric_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_lyric_line).toList();
  }

  @protected
  List<MusicInfo> dco_decode_list_music_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_music_info).toList();
  }

  @protected
  List<PlaylistInfo> dco_decode_list_playlist_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_playlist_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  LyricLine dco_decode_lyric_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LyricLine(
      timeMs: dco_decode_i_32(arr[0]),
      text: dco_decode_String(arr[1]),
    );
  }

  @protected
  MusicInfo dco_decode_music_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return MusicInfo(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      artist: dco_decode_opt_String(arr[2]),
      album: dco_decode_opt_String(arr[3]),
      durationMs: dco_decode_i_64(arr[4]),
      coverPath: dco_decode_opt_String(arr[5]),
      lyrics: dco_decode_opt_String(arr[6]),
      path: dco_decode_String(arr[7]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  MusicInfo? dco_decode_opt_box_autoadd_music_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_music_info(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  PlaylistInfo dco_decode_playlist_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return PlaylistInfo(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      description: dco_decode_opt_String(arr[2]),
      coverPath: dco_decode_opt_String(arr[3]),
      isSystem: dco_decode_i_32(arr[4]),
      createdAt: dco_decode_i_64(arr[5]),
      updatedAt: dco_decode_i_64(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  DbManager
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DbManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  DbManager
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DbManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  DbManager
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DbManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<AudioMetadata> sse_decode_StreamSink_audio_metadata_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AudioInfo sse_decode_audio_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_String(deserializer);
    var var_album = sse_decode_String(deserializer);
    var var_durationSeconds = sse_decode_u_32(deserializer);
    var var_coverArt = sse_decode_opt_list_prim_u_8_strict(deserializer);
    return AudioInfo(
      title: var_title,
      artist: var_artist,
      album: var_album,
      durationSeconds: var_durationSeconds,
      coverArt: var_coverArt,
    );
  }

  @protected
  AudioMetadata sse_decode_audio_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_String(deserializer);
    var var_album = sse_decode_String(deserializer);
    var var_durationSeconds = sse_decode_u_32(deserializer);
    var var_path = sse_decode_String(deserializer);
    return AudioMetadata(
      title: var_title,
      artist: var_artist,
      album: var_album,
      durationSeconds: var_durationSeconds,
      path: var_path,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  MusicInfo sse_decode_box_autoadd_music_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_music_info(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<LyricLine> sse_decode_list_lyric_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LyricLine>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_lyric_line(deserializer));
    }
    return ans_;
  }

  @protected
  List<MusicInfo> sse_decode_list_music_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MusicInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_music_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<PlaylistInfo> sse_decode_list_playlist_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PlaylistInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_playlist_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  LyricLine sse_decode_lyric_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timeMs = sse_decode_i_32(deserializer);
    var var_text = sse_decode_String(deserializer);
    return LyricLine(timeMs: var_timeMs, text: var_text);
  }

  @protected
  MusicInfo sse_decode_music_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_opt_String(deserializer);
    var var_album = sse_decode_opt_String(deserializer);
    var var_durationMs = sse_decode_i_64(deserializer);
    var var_coverPath = sse_decode_opt_String(deserializer);
    var var_lyrics = sse_decode_opt_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    return MusicInfo(
      id: var_id,
      title: var_title,
      artist: var_artist,
      album: var_album,
      durationMs: var_durationMs,
      coverPath: var_coverPath,
      lyrics: var_lyrics,
      path: var_path,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MusicInfo? sse_decode_opt_box_autoadd_music_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_music_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlaylistInfo sse_decode_playlist_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_coverPath = sse_decode_opt_String(deserializer);
    var var_isSystem = sse_decode_i_32(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return PlaylistInfo(
      id: var_id,
      name: var_name,
      description: var_description,
      coverPath: var_coverPath,
      isSystem: var_isSystem,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
    DbManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as DbManagerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
    DbManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as DbManagerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbManager(
    DbManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as DbManagerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_audio_metadata_Sse(
    RustStreamSink<AudioMetadata> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_audio_metadata,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_audio_info(AudioInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.artist, serializer);
    sse_encode_String(self.album, serializer);
    sse_encode_u_32(self.durationSeconds, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.coverArt, serializer);
  }

  @protected
  void sse_encode_audio_metadata(AudioMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.artist, serializer);
    sse_encode_String(self.album, serializer);
    sse_encode_u_32(self.durationSeconds, serializer);
    sse_encode_String(self.path, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_music_info(
    MusicInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_music_info(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_lyric_line(
    List<LyricLine> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_lyric_line(item, serializer);
    }
  }

  @protected
  void sse_encode_list_music_info(
    List<MusicInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_music_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_playlist_info(
    List<PlaylistInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_playlist_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_lyric_line(LyricLine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.timeMs, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_music_info(MusicInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.artist, serializer);
    sse_encode_opt_String(self.album, serializer);
    sse_encode_i_64(self.durationMs, serializer);
    sse_encode_opt_String(self.coverPath, serializer);
    sse_encode_opt_String(self.lyrics, serializer);
    sse_encode_String(self.path, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_music_info(
    MusicInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_music_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_playlist_info(PlaylistInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_opt_String(self.coverPath, serializer);
    sse_encode_i_32(self.isSystem, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class DbManagerImpl extends RustOpaque implements DbManager {
  // Not to be used by end users
  DbManagerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  DbManagerImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_DbManager,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_DbManager,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_DbManagerPtr,
  );

  /// 向歌单中添加一首歌曲（附带排序权重）
  Future<void> addSongToPlaylist({
    required String playlistId,
    required String musicId,
  }) => RustLib.instance.api.crateApiAudioDbDbManagerAddSongToPlaylist(
    that: this,
    playlistId: playlistId,
    musicId: musicId,
  );

  /// 记录一次播放历史，并自动执行“滑动窗口”裁剪
  Future<void> addToHistory({required String musicId}) => RustLib.instance.api
      .crateApiAudioDbDbManagerAddToHistory(that: this, musicId: musicId);

  /// 清空播放历史
  Future<void> clearHistory() =>
      RustLib.instance.api.crateApiAudioDbDbManagerClearHistory(that: this);

  /// 创建一个新歌单
  Future<void> createPlaylist({
    required String name,
    String? description,
    required bool isSystem,
  }) => RustLib.instance.api.crateApiAudioDbDbManagerCreatePlaylist(
    that: this,
    name: name,
    description: description,
    isSystem: isSystem,
  );

  /// 删除指定歌单
  /// ⚠️ 无外键约束，必须手动用事务清除该歌单下的关联映射记录
  Future<void> deletePlaylist({required String playlistId}) =>
      RustLib.instance.api.crateApiAudioDbDbManagerDeletePlaylist(
        that: this,
        playlistId: playlistId,
      );

  /// 核心逻辑：从媒体库彻底删除歌曲
  /// ⚠️ 由于无外键约束，需要手动清理交叉连接表和播放历史
  Future<void> deleteSongCompletely({required String musicId}) =>
      RustLib.instance.api.crateApiAudioDbDbManagerDeleteSongCompletely(
        that: this,
        musicId: musicId,
      );

  /// 获取所有歌单（包括自建和系统歌单）
  Future<List<PlaylistInfo>> getAllPlaylists() =>
      RustLib.instance.api.crateApiAudioDbDbManagerGetAllPlaylists(that: this);

  /// 3. 获取所有收藏的歌曲列表
  /// ✨ 同样利用 INNER JOIN 自动屏蔽掉无外键可能带来的脏数据
  Future<List<MusicInfo>> getFavoriteSongs() =>
      RustLib.instance.api.crateApiAudioDbDbManagerGetFavoriteSongs(that: this);

  /// 获取最近播放的历史歌曲列表
  Future<List<MusicInfo>> getPlayHistory() =>
      RustLib.instance.api.crateApiAudioDbDbManagerGetPlayHistory(that: this);

  /// 获取单首歌曲
  Future<MusicInfo?> getSong({required String id}) =>
      RustLib.instance.api.crateApiAudioDbDbManagerGetSong(that: this, id: id);

  /// 获取某个歌单内所有歌曲的 ID 列表（轻量级查询）
  Future<List<String>> getSongIdsInPlaylist({required String playlistId}) =>
      RustLib.instance.api.crateApiAudioDbDbManagerGetSongIdsInPlaylist(
        that: this,
        playlistId: playlistId,
      );

  /// 核心查询：基于 INNER JOIN 获取特定歌单内的所有歌曲
  /// ✨ 即使数据由于没有外键产生了残留不一致，INNER JOIN 也会自动过滤非法的 music_id
  Future<List<MusicInfo>> getSongsInPlaylist({required String playlistId}) =>
      RustLib.instance.api.crateApiAudioDbDbManagerGetSongsInPlaylist(
        that: this,
        playlistId: playlistId,
      );

  /// 插入或更新单首歌曲
  Future<void> insertSong({required MusicInfo music}) => RustLib.instance.api
      .crateApiAudioDbDbManagerInsertSong(that: this, music: music);

  /// 批量增量扫描歌曲（高效率事务处理）
  Future<void> insertSongsBulk({required List<MusicInfo> songs}) => RustLib
      .instance
      .api
      .crateApiAudioDbDbManagerInsertSongsBulk(that: this, songs: songs);

  /// 1. 检查某首歌曲是否已被收藏
  Future<bool> isSongFavorited({required String musicId}) => RustLib
      .instance
      .api
      .crateApiAudioDbDbManagerIsSongFavorited(that: this, musicId: musicId);

  /// 从指定歌单中移除一首歌曲
  Future<void> removeSongFromPlaylist({
    required String playlistId,
    required String musicId,
  }) => RustLib.instance.api.crateApiAudioDbDbManagerRemoveSongFromPlaylist(
    that: this,
    playlistId: playlistId,
    musicId: musicId,
  );

  /// 2. 切换收藏状态 (Toggle 逻辑)
  /// 如果已收藏则取消收藏，如果未收藏则加入收藏
  Future<bool> toggleSongFavorite({required String musicId}) => RustLib
      .instance
      .api
      .crateApiAudioDbDbManagerToggleSongFavorite(that: this, musicId: musicId);

  /// 修改歌单信息
  Future<void> updatePlaylist({
    required String name,
    String? description,
    String? coverPath,
  }) => RustLib.instance.api.crateApiAudioDbDbManagerUpdatePlaylist(
    that: this,
    name: name,
    description: description,
    coverPath: coverPath,
  );
}
