// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DbManager>>
abstract class DbManager implements RustOpaqueInterface {
  Future<MusicInfo?> getSong({required String id});

  /// 插入一首新歌
  Future<void> insertSong({required MusicInfo music});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// 初始化数据库并建表
  static Future<DbManager> newInstance({required String dbPath}) =>
      RustLib.instance.api.crateApiAudioDbDbManagerNew(dbPath: dbPath);
}

class MusicInfo {
  final String id;
  final String title;
  final String artist;
  final String? album;
  final PlatformInt64 durationMs;
  final String? coverPath;
  final String? lyrics;
  final String path;

  const MusicInfo({
    required this.id,
    required this.title,
    required this.artist,
    this.album,
    required this.durationMs,
    this.coverPath,
    this.lyrics,
    required this.path,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationMs.hashCode ^
      coverPath.hashCode ^
      lyrics.hashCode ^
      path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MusicInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationMs == other.durationMs &&
          coverPath == other.coverPath &&
          lyrics == other.lyrics &&
          path == other.path;
}
