// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_attr`, `parse_lrc_inner`, `parse_ttml_time`, `parse_ttml`, `try_read_metadata_json`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// 根据内容自动检测歌词格式
Future<LyricFormat> detectLyricFormat({required String content}) =>
    RustLib.instance.api.crateApiAudioInfoDetectLyricFormat(content: content);

/// 读取任意受支持音频格式（MP3 / FLAC / M4A / OGG …）的完整元数据。
/// 当音频内嵌标签缺失时，优先使用同级目录下的 `metadata.json` 作为备选。
///
/// # 错误
/// 返回 `Err(String)` 描述第一个遇到的错误。
Future<AudioInfo> getAudioInfo({required String path}) =>
    RustLib.instance.api.crateApiAudioInfoGetAudioInfo(path: path);

Future<Uint8List?> getExternalCover({required String audioPath}) => RustLib
    .instance
    .api
    .crateApiAudioInfoGetExternalCover(audioPath: audioPath);

/// 读取歌词文件内容，用于 Dart 端获取 metadata.json 中 lyric_path 指向的完整歌词文本。
///
/// # Arguments
/// * `lyric_path` - 歌词文件的完整路径（支持 .lrc / .ttml / .xml）
///
/// # Returns
/// * `Ok(Some(String))` - 读取到的歌词文本内容
/// * `Ok(None)` - 文件不存在或读取失败
/// * `Err(String)` - 路径参数为空
Future<String?> readLrcFile({required String lyricPath}) =>
    RustLib.instance.api.crateApiAudioInfoReadLrcFile(lyricPath: lyricPath);

/// 从音频文件中读取到的完整元数据
class AudioInfo {
  final String title;
  final String artist;
  final String album;
  final int durationSeconds;

  /// 封面图片的原始字节（JPEG / PNG），若无则为 None
  final Uint8List? coverArt;

  /// 从 metadata.json 的 lyric_path 中读取的歌词原始文本内容（如有）
  final String? lyricRawContent;

  const AudioInfo({
    required this.title,
    required this.artist,
    required this.album,
    required this.durationSeconds,
    this.coverArt,
    this.lyricRawContent,
  });

  /// 根据原始歌词内容自动检测格式（LRC 或 TTML）并解析。
  /// 返回解析后的 `Vec<LyricLine>`，TTML 格式会携带逐词信息。
  static Future<List<LyricLine>> parseLyrics({String? lyricRawContent}) =>
      RustLib.instance.api.crateApiAudioInfoAudioInfoParseLyrics(
        lyricRawContent: lyricRawContent,
      );

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationSeconds.hashCode ^
      coverArt.hashCode ^
      lyricRawContent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationSeconds == other.durationSeconds &&
          coverArt == other.coverArt &&
          lyricRawContent == other.lyricRawContent;
}

/// 歌词格式枚举
enum LyricFormat { lrc, ttml, unknown }

/// 一行歌词（支持逐词时间戳）
class LyricLine {
  final int timeMs;

  /// 整行持续时长（ms），TTML 可提供，LRC 填 0
  final int durationMs;
  final String text;

  /// 逐词信息，仅 TTML 格式提供；LRC 格式为空
  final List<LyricWord> words;

  const LyricLine({
    required this.timeMs,
    required this.durationMs,
    required this.text,
    required this.words,
  });

  @override
  int get hashCode =>
      timeMs.hashCode ^ durationMs.hashCode ^ text.hashCode ^ words.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricLine &&
          runtimeType == other.runtimeType &&
          timeMs == other.timeMs &&
          durationMs == other.durationMs &&
          text == other.text &&
          words == other.words;
}

/// 逐词高亮所需的单个词信息
class LyricWord {
  final String text;
  final int startMs;
  final int endMs;

  const LyricWord({
    required this.text,
    required this.startMs,
    required this.endMs,
  });

  @override
  int get hashCode => text.hashCode ^ startMs.hashCode ^ endMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricWord &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          startMs == other.startMs &&
          endMs == other.endMs;
}
