// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `try_read_metadata_json`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 读取任意受支持音频格式（MP3 / FLAC / M4A / OGG …）的完整元数据。
/// 当音频内嵌标签缺失时，优先使用同级目录下的 `metadata.json` 作为备选。
///
/// # 错误
/// 返回 `Err(String)` 描述第一个遇到的错误。
Future<AudioInfo> getAudioInfo({required String path}) =>
    RustLib.instance.api.crateApiAudioInfoGetAudioInfo(path: path);

Future<Uint8List?> getExternalCover({required String audioPath}) => RustLib
    .instance
    .api
    .crateApiAudioInfoGetExternalCover(audioPath: audioPath);

/// 读取歌词文件内容，用于 Dart 端获取 metadata.json 中 lyric_path 指向的完整 LRC 文本。
///
/// # Arguments
/// * `lyric_path` - LRC 文件的完整路径
///
/// # Returns
/// * `Ok(Some(String))` - 读取到的 LRC 文本内容
/// * `Ok(None)` - 文件不存在或读取失败
/// * `Err(String)` - 路径参数为空
Future<String?> readLrcFile({required String lyricPath}) =>
    RustLib.instance.api.crateApiAudioInfoReadLrcFile(lyricPath: lyricPath);

/// 从音频文件中读取到的完整元数据
class AudioInfo {
  final String title;
  final String artist;
  final String album;
  final int durationSeconds;

  /// 封面图片的原始字节（JPEG / PNG），若无则为 None
  final Uint8List? coverArt;

  /// 从 metadata.json 的 lyric_path 中读取的 LRC 歌词内容（如有）
  final String? lrcContent;

  const AudioInfo({
    required this.title,
    required this.artist,
    required this.album,
    required this.durationSeconds,
    this.coverArt,
    this.lrcContent,
  });

  static Future<List<LyricLine>> parseLrc({String? lrcContent}) => RustLib
      .instance
      .api
      .crateApiAudioInfoAudioInfoParseLrc(lrcContent: lrcContent);

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationSeconds.hashCode ^
      coverArt.hashCode ^
      lrcContent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationSeconds == other.durationSeconds &&
          coverArt == other.coverArt &&
          lrcContent == other.lrcContent;
}

class LyricLine {
  final int timeMs;
  final String text;

  const LyricLine({required this.timeMs, required this.text});

  @override
  int get hashCode => timeMs.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricLine &&
          runtimeType == other.runtimeType &&
          timeMs == other.timeMs &&
          text == other.text;
}
