// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DbManager>>
abstract class DbManager implements RustOpaqueInterface {
  /// 向歌单中添加一首歌曲（附带排序权重）
  Future<void> addSongToPlaylist({
    required String playlistId,
    required String musicId,
  });

  /// 记录一次播放历史，并自动执行“滑动窗口”裁剪
  Future<void> addToHistory({
    required String musicId,
    required PlatformInt64 maxLimit,
  });

  /// 清空播放历史
  Future<void> clearHistory();

  Future<void> clearQueueHistory();

  /// 创建一个新歌单（让 Rust 自动生成唯一 ID 并返回给前端）
  Future<String> createPlaylist({
    required String name,
    String? description,
    String? coverPath,
    required bool isSystem,
  });

  /// 删除指定歌单
  /// ⚠️ 无外键约束，必须手动用事务清除该歌单下的关联映射记录
  Future<void> deletePlaylist({required String playlistId});

  Future<void> deleteQueueSnapshot({required String snapshotId});

  /// 核心逻辑：从媒体库彻底删除歌曲
  /// ⚠️ 由于无外键约束，需要手动清理交叉连接表和播放历史
  Future<void> deleteSongCompletely({required String musicId});

  /// 获取所有歌单（包含每张歌单的歌曲 ID 列表）
  /// 获取所有歌单（包含每张歌单的歌曲 ID 列表）
  Future<List<PlaylistInfo>> getAllPlaylists();

  /// 3. 获取所有收藏的歌曲列表
  /// 同样利用 INNER JOIN 自动屏蔽掉无外键可能带来的脏数据
  Future<List<MusicInfo>> getFavoriteSongs();

  /// 获取最近播放的歌曲 ID 列表（按播放时间倒序）
  Future<List<String>> getPlayHistory();

  /// 获取队列快照历史列表
  Future<List<QueueSnapshot>> getQueueHistory({required PlatformInt64 limit});

  /// 获取单首歌曲
  Future<MusicInfo?> getSong({required String id});

  /// 获取某个歌单内所有歌曲的 ID 列表（轻量级查询）
  Future<List<String>> getSongIdsInPlaylist({required String playlistId});

  /// 核心查询：基于 INNER JOIN 获取特定歌单内的所有歌曲
  /// ✨ 即使数据由于没有外键产生了残留不一致，INNER JOIN 也会自动过滤非法的 music_id
  Future<List<MusicInfo>> getSongsInPlaylist({required String playlistId});

  /// 插入或更新单首歌曲
  Future<void> insertSong({required MusicInfo music});

  /// 批量增量扫描歌曲（高效率事务处理）
  Future<void> insertSongsBulk({required List<MusicInfo> songs});

  /// 1. 检查某首歌曲是否已被收藏
  Future<bool> isSongFavorited({required String musicId});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DbManager> newInstance({required String dbPath}) =>
      RustLib.instance.api.crateApiAudioDbDbManagerNew(dbPath: dbPath);

  /// 从指定歌单中移除一首歌曲
  Future<void> removeSongFromPlaylist({
    required String playlistId,
    required String musicId,
  });

  /// 保存一个新的队列快照，并在 Rust 侧控制滑动窗口（保存上限 max_limit）
  Future<String> saveQueueSnapshot({
    required List<String> songs,
    required PlatformInt64 currentIndex,
    required PlatformInt64 maxLimit,
  });

  /// 2. 切换收藏状态 (Toggle 逻辑)
  /// 如果已收藏则取消收藏，如果未收藏则加入收藏
  Future<bool> toggleSongFavorite({required String musicId});

  /// 修改歌单信息
  Future<void> updatePlaylist({
    required String id,
    required String name,
    String? description,
    String? coverPath,
  });
}

class MusicInfo {
  final String id;
  final String title;
  final String? artist;
  final String? album;
  final PlatformInt64 durationMs;
  final String? coverPath;
  final String? lyrics;
  final String path;

  const MusicInfo({
    required this.id,
    required this.title,
    this.artist,
    this.album,
    required this.durationMs,
    this.coverPath,
    this.lyrics,
    required this.path,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationMs.hashCode ^
      coverPath.hashCode ^
      lyrics.hashCode ^
      path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MusicInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationMs == other.durationMs &&
          coverPath == other.coverPath &&
          lyrics == other.lyrics &&
          path == other.path;
}

class PlaylistInfo {
  final String id;
  final String name;
  final String? description;
  final String? coverPath;
  final int isSystem;
  final List<String> ids;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const PlaylistInfo({
    required this.id,
    required this.name,
    this.description,
    this.coverPath,
    required this.isSystem,
    required this.ids,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      coverPath.hashCode ^
      isSystem.hashCode ^
      ids.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          coverPath == other.coverPath &&
          isSystem == other.isSystem &&
          ids == other.ids &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// 队列快照模型
class QueueSnapshot {
  final String id;
  final List<String> songs;
  final PlatformInt64 currentIndex;
  final PlatformInt64 createdAt;

  const QueueSnapshot({
    required this.id,
    required this.songs,
    required this.currentIndex,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ songs.hashCode ^ currentIndex.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueueSnapshot &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          songs == other.songs &&
          currentIndex == other.currentIndex &&
          createdAt == other.createdAt;
}
