// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Read and parse a metadata.json file from the given directory path.
///
/// Looks for `metadata.json` inside the provided directory (typically a
/// song-specific folder like `M3Music/歌曲名 - 歌手名/`).
///
/// # Arguments
/// * `dir_path` - Path to the directory containing metadata.json
///
/// # Returns
/// * `Ok(SongMetadata)` on successful parse
/// * `Err(String)` describing what went wrong
Future<SongMetadata> readMetadata({required String dirPath}) =>
    RustLib.instance.api.crateApiMetadataReadMetadata(dirPath: dirPath);

/// Represents the metadata.json file stored alongside downloaded songs.
/// Contains local file paths to the downloaded audio, lyrics, and cover image.
class SongMetadata {
  final String id;
  final String title;
  final String author;
  final String source;

  /// Local path to the downloaded audio file (e.g. .../歌曲名 - 歌手名.mp3)
  final String audioPath;

  /// Local path to the downloaded lyrics file, if available (e.g. .../歌曲名 - 歌手名.lrc)
  final String? lyricPath;

  /// Local path to the downloaded cover image, if available (e.g. .../cover.jpg)
  final String? coverPath;

  const SongMetadata({
    required this.id,
    required this.title,
    required this.author,
    required this.source,
    required this.audioPath,
    this.lyricPath,
    this.coverPath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      author.hashCode ^
      source.hashCode ^
      audioPath.hashCode ^
      lyricPath.hashCode ^
      coverPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongMetadata &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          author == other.author &&
          source == other.source &&
          audioPath == other.audioPath &&
          lyricPath == other.lyricPath &&
          coverPath == other.coverPath;
}
