// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `is_audio_file`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 并行递归扫描 `dir_path`，通过 StreamSink 实时推送到 Flutter Dart 端
Stream<AudioMetadata> scanDirectoryParallel({required String dirPath}) =>
    RustLib.instance.api.crateApiScannerScanDirectoryParallel(dirPath: dirPath);

class AudioMetadata {
  final String title;
  final String artist;
  final String album;
  final int durationSeconds;
  final String path;

  const AudioMetadata({
    required this.title,
    required this.artist,
    required this.album,
    required this.durationSeconds,
    required this.path,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationSeconds.hashCode ^
      path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioMetadata &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationSeconds == other.durationSeconds &&
          path == other.path;
}
